Step 1 : Importing the libraries
Step 2 : Reading the dataset
Step 3 : Seperating the features and target
Step 4 : Splitting the dataset into training set and test
Step 5 : Creating the Model
Step 6 : Training Model 
Step 7 : Testing the Model
Step 8 : Check for accuracy
Step 9 : Confusion Matrix

# Step 1 : Importing the libraries

In [1]:
import numpy as np
import pandas as pd

# Step 2 : Reading the dataset

In [2]:
dataset = pd.read_csv("cancer_dataset.csv") # first we need upload the dataset
dataset # will shoe first 5 rows

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

# Step 3 : Seperating the features and target

In [3]:
x = dataset.iloc[:,2:32]
y = dataset.iloc[:,1]
x.head(10)

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678
5,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,0.2087,0.07613,...,15.47,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440
6,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,0.1794,0.05742,...,22.88,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368
7,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,0.2196,0.07451,...,17.06,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.1556,0.3196,0.11510
8,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,0.2350,0.07389,...,15.49,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.2060,0.4378,0.10720
9,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,0.2030,0.08243,...,15.09,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.2210,0.4366,0.20750

In [4]:
y.head()

0    M
1    M
2    M
3    M
4    M
Name: diagnosis, dtype: object

# Step 4 : Splitting the dataset into training set and test

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=42)

# Step 5 : Creating the Model

In [6]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

# Step 6 : Training Model

In [7]:
model.fit(x_train,y_train)

GaussianNB()

# Step 7 : Testing the Model

In [8]:
y_pred = model.predict(x_test) # predicting for all x_test
y_pred

array(['B', 'M', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'B',
       'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M',
       'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'M', 'M', 'B', 'B',
       'B', 'M', 'M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'M', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'M'], dtype='<U1')

In [9]:
y_test

204    B
70     M
131    M
431    B
540    B
      ..
486    B
75     M
249    B
238    B
265    M
Name: diagnosis, Length: 114, dtype: object

In [10]:
y_pred

array(['B', 'M', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'B',
       'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M',
       'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'M', 'M', 'B', 'B',
       'B', 'M', 'M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'M', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'M'], dtype='<U1')

In [11]:
list(zip(y_test,y_pred))

[('B', 'B'),
 ('M', 'M'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('M', 'M'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('B', 'B'),
 ('M', 'M'),
 ('B', 'B'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('M', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('B', 'B'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('M', 'M'),
 ('B', 'B'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('B', 'B'),
 ('M', 'B'),
 ('M', 'M'),
 ('M', 'M'),
 ('M', 'M'),
 ('M', 'M'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('M', 'M'),
 ('B', 'B'),
 ('M', 'M'),
 ('M', 'M'),
 ('B', 'B'),
 ('M', 'M'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M'),
 ('B', 'B'),
 ('B', 'B'),
 ('M', 'M')]

# Step 8 : Check for accuracy

In [12]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,y_pred)
print(acc*100)

97.36842105263158

# Step 9 : Confusion Matrix

In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[71  0]
 [ 3 40]]